version: 2

models:
  - name: stg_akahu_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]

  - name: stg_akahu_account_balances
    columns:
      - name: account_id
        tests: [not_null]
      - name: snapshot_date
        tests: [not_null]

  - name: fct_account_daily_balances
    columns:
      - name: account_id
        tests: [not_null]
      - name: snapshot_date
        tests: [not_null]

  - name: fct_mortgage_over_time
    columns:
      - name: snapshot_date
        tests: [not_null]

  - name: dim_loan_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
