{{ config(materialized='view') }}

-- Flatten key account fields; retain loan details for mortgage analysis
with src as (
    select * from {{ source('akahu_raw', 'accounts') }}
)
select
  _id as account_id,
  name as account_name,
  upper(trim(coalesce(type,''))) as account_type,
  case
    when lower(coalesce(type,'')) like '%credit%' or lower(coalesce(type,'')) like '%card%' then true
    else false
  end as is_credit_card,
  status,
  -- Flattened loan details columns generated by dlt
  nullif(meta__loan_details__interest__rate::text,'')::numeric as loan_interest_rate,
  meta__loan_details__interest__type as loan_interest_type,
  nullif(meta__loan_details__interest__expires_at::text,'')::timestamptz as loan_interest_expires_at,
  nullif(meta__loan_details__is_interest_only::text,'')::boolean as is_interest_only,
  nullif(meta__loan_details__term__years::text,'')::int as term_years,
  nullif(meta__loan_details__term__months::text,'')::int as term_months,
  nullif(meta__loan_details__matures_at::text,'')::timestamptz as loan_matures_at,
  nullif(meta__loan_details__initial_principal::text,'')::numeric as loan_initial_principal,
  meta__loan_details__repayment__frequency as repayment_frequency,
  nullif(meta__loan_details__repayment__next_date::text,'')::timestamptz as repayment_next_date,
  coalesce(nullif(meta__loan_details__repayment__next_amount::text,'')::numeric, meta__loan_details__repayment__next_amount__v_double::numeric) as repayment_next_amount,
  _dlt_load_id
from src
where _id is not null
